/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/tanalam2411/olms/pkg/api/client/clientset/versioned/scheme"
	v1alpha1 "github.com/tanalam2411/olms/pkg/api/olms/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OLMSsGetter has a method to return a OLMSInterface.
// A group's client should implement this interface.
type OLMSsGetter interface {
	OLMSs(namespace string) OLMSInterface
}

// OLMSInterface has methods to work with OLMS resources.
type OLMSInterface interface {
	Create(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.CreateOptions) (*v1alpha1.OLMS, error)
	Update(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.UpdateOptions) (*v1alpha1.OLMS, error)
	UpdateStatus(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.UpdateOptions) (*v1alpha1.OLMS, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.OLMS, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OLMSList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OLMS, err error)
	OLMSExpansion
}

// oLMSs implements OLMSInterface
type oLMSs struct {
	client rest.Interface
	ns     string
}

// newOLMSs returns a OLMSs
func newOLMSs(c *OlmsV1alpha1Client, namespace string) *oLMSs {
	return &oLMSs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the oLMS, and returns the corresponding oLMS object, and an error if there is any.
func (c *oLMSs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OLMS, err error) {
	result = &v1alpha1.OLMS{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("olmss").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OLMSs that match those selectors.
func (c *oLMSs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OLMSList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OLMSList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("olmss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested oLMSs.
func (c *oLMSs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("olmss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a oLMS and creates it.  Returns the server's representation of the oLMS, and an error, if there is any.
func (c *oLMSs) Create(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.CreateOptions) (result *v1alpha1.OLMS, err error) {
	result = &v1alpha1.OLMS{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("olmss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oLMS).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a oLMS and updates it. Returns the server's representation of the oLMS, and an error, if there is any.
func (c *oLMSs) Update(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.UpdateOptions) (result *v1alpha1.OLMS, err error) {
	result = &v1alpha1.OLMS{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("olmss").
		Name(oLMS.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oLMS).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *oLMSs) UpdateStatus(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.UpdateOptions) (result *v1alpha1.OLMS, err error) {
	result = &v1alpha1.OLMS{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("olmss").
		Name(oLMS.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oLMS).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the oLMS and deletes it. Returns an error if one occurs.
func (c *oLMSs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("olmss").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *oLMSs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("olmss").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched oLMS.
func (c *oLMSs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OLMS, err error) {
	result = &v1alpha1.OLMS{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("olmss").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
