/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tanalam2411/olms/pkg/api/olms/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOLMSs implements OLMSInterface
type FakeOLMSs struct {
	Fake *FakeOlmsV1alpha1
	ns   string
}

var olmssResource = schema.GroupVersionResource{Group: "olms", Version: "v1alpha1", Resource: "olmss"}

var olmssKind = schema.GroupVersionKind{Group: "olms", Version: "v1alpha1", Kind: "OLMS"}

// Get takes name of the oLMS, and returns the corresponding oLMS object, and an error if there is any.
func (c *FakeOLMSs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OLMS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(olmssResource, c.ns, name), &v1alpha1.OLMS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OLMS), err
}

// List takes label and field selectors, and returns the list of OLMSs that match those selectors.
func (c *FakeOLMSs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OLMSList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(olmssResource, olmssKind, c.ns, opts), &v1alpha1.OLMSList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OLMSList{ListMeta: obj.(*v1alpha1.OLMSList).ListMeta}
	for _, item := range obj.(*v1alpha1.OLMSList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oLMSs.
func (c *FakeOLMSs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(olmssResource, c.ns, opts))

}

// Create takes the representation of a oLMS and creates it.  Returns the server's representation of the oLMS, and an error, if there is any.
func (c *FakeOLMSs) Create(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.CreateOptions) (result *v1alpha1.OLMS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(olmssResource, c.ns, oLMS), &v1alpha1.OLMS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OLMS), err
}

// Update takes the representation of a oLMS and updates it. Returns the server's representation of the oLMS, and an error, if there is any.
func (c *FakeOLMSs) Update(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.UpdateOptions) (result *v1alpha1.OLMS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(olmssResource, c.ns, oLMS), &v1alpha1.OLMS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OLMS), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOLMSs) UpdateStatus(ctx context.Context, oLMS *v1alpha1.OLMS, opts v1.UpdateOptions) (*v1alpha1.OLMS, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(olmssResource, "status", c.ns, oLMS), &v1alpha1.OLMS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OLMS), err
}

// Delete takes name of the oLMS and deletes it. Returns an error if one occurs.
func (c *FakeOLMSs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(olmssResource, c.ns, name), &v1alpha1.OLMS{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOLMSs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(olmssResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OLMSList{})
	return err
}

// Patch applies the patch and returns the patched oLMS.
func (c *FakeOLMSs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OLMS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(olmssResource, c.ns, name, pt, data, subresources...), &v1alpha1.OLMS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OLMS), err
}
